### ISSUE TITLE
ValueError while runing trn.py

### ISSUE THREAD

**Issue by aldiak** [hkaggarwal/modl#10]
Hello sir, I am getting the following error from lines 147-151 of the trn.py file:

Successfully undersampled data
Traceback (most recent call last):
  File "run.py", line 94, in <module>
    capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs]
  File "run.py", line 94, in <listcomp>
    capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs]
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\ops\clip_ops.py", line 69, in clip_by_value
    t = ops.convert_to_tensor(t, name="t")
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 454, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

**Comment by aldiak** [comment]
> Hello sir, I am getting the following error from lines 147-151 of the trn.py file:
> 
> Successfully undersampled data Traceback (most recent call last): File "run.py", line 94, in capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs] File "run.py", line 94, in capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs] File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper return target(*args, **kwargs) File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\ops\clip_ops.py", line 69, in clip_by_value t = ops.convert_to_tensor(t, name="t") File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1039, in convert_to_tensor return convert_to_tensor_v2(value, dtype, preferred_dtype, name) File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1097, in convert_to_tensor_v2 as_ref=False) File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1175, in internal_convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function return constant(v, dtype=dtype, name=name) File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant allow_broadcast=True) File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl allow_broadcast=allow_broadcast)) File "C:\Users\Alou\anaconda3\envs\research_gpu\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 454, in make_tensor_proto raise ValueError("None values not supported.") ValueError: None values not supported.
